name: Feature request
description: Suggest an improvement or new feature for the Resize Mobile Split View plugin
labels:
  - Feature request
  - '⚪️ Pending'
body:
  - type: markdown
    attributes:
      value: '**Note:** If English is not your first language, please consider using AI tools like ChatGPT to translate your responses.'
  - type: checkboxes
    id: checklist
    attributes:
      label: Enhancement checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have updated to the latest versions of Obsidian, Obsidian installer, and Resize Mobile Split View
          required: true
  - type: markdown
    attributes:
      value: '&#8203;'
  - type: markdown
    attributes:
      value: '## Required'
  - type: textarea
    id: use-case
    attributes:
      label: Use case or problem
      description: What's your use case for this feature? In other words, what are you trying to accomplish when you realize you need this feature?
      placeholder: Describe use case or problem here...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: The meat of the feature request. How do you think we should implement this feature and how would this solve your problem?
      placeholder: Describe solution here...
    validations:
      required: true
  - type: markdown
    attributes:
      value: '&#8203;'
  - type: markdown
    attributes:
      value: '## Optional'
  - type: textarea
    id: workaround
    attributes:
      label: Current workaround
      description: If you're using any workarounds, it might be helpful to us to get some inspiration.
      placeholder: Describe workaround here...
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Provide any additional information that you think would be helpful to understand your suggestion.
      placeholder: Add additional information here...
    validations:
      required: false
  - type: textarea
    id: debug-info
    attributes:
      label: Debug information
      description: |-
        To share your Obsidian debug info:

        1. Open Command palette.
        2. Search for then select **Show debug info**.
        3. Press **Copy to clipboard**.
        4. Paste the copied text here.
      placeholder: Paste debug info here...
      render: text
    validations:
      required: false
